# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eks_cluster.cluster:
resource "aws_eks_cluster" "cluster" {
  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]
  name       = var.cluster-name

  role_arn   = var.cluster_service_role_arn
  tags       = {}
  version    = "1.20"

  timeouts {}

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access  = false
    public_access_cidrs = [
      "0.0.0.0/0",
    ]
    security_group_ids = [
      var.cluster-sg,
    ]
    subnet_ids = [
      var.sub-priv1,
      var.sub-priv2,
      var.sub-priv3,
    ]
  }
  encryption_config  {
    provider  {
      key_arn = aws_kms_key.ekskey.arn
    }
    resources = ["secrets"]
  }

}

